import Head from 'next/head';
import MainHome from './home';

export default function Home() {
	return (
		<>
			<Head>
				<title>Infinity || Home Page</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Main Home page */}
			<MainHome />
		</>
	);
}
